<?php
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}
require_once '../config/db.php';
include('../includes/header.php');
?>

<style>
    .accordion-item .accordion-body {
        background-color: #f6f3ee;
        border: 1px solid #e0c8b6;
    }

    .accordion-item {
        border-radius: 8px !important;
        margin-bottom: 12px;
        overflow: hidden;
    }
</style>

<div class="container my-5">
    <h1 class="text-center mb-4">Frequently Asked Questions (FAQs)</h1>
    <h4 class="text-center text-muted mb-5">for Makan Mystery Marketplace</h4>

    <div class="accordion" id="faqAccordion">

        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                    What is a Mystery Box?
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
                data-bs-parent="#faqAccordion">
                <div class="accordion-body">
                    A Mystery Box contains delicious surplus food items from our vendor partners (hotels, restaurants,
                    bakeries and cafes) that would otherwise go to waste. The exact contents are unknown when you order,
                    but the box value is always significantly higher than the price you pay. It's a great way to save
                    food and money!
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Why does the stock run out so quickly?
                </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo"
                data-bs-parent="#faqAccordion">
                <div class="accordion-body">
                    Stock is based purely on the <b>surplus</b> generated by our vendor partners that day. This means
                    quantities are very limited and highly sought after.
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="headingThree">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    How do I collect my order? (Crucial for Local Pickup)
                </button>
            </h2>
            <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree"
                data-bs-parent="#faqAccordion">
                <div class="accordion-body">
                    <p>Makan Mystery is a <b>local pickup service</b>. After placing your order and receiving the status
                        "Ready for Pick-up," please follow these steps:</p>
                    <ol>
                        <li>Go to your <b>Account</b> page.</li>
                        <li>Navigate to your <b>Orders</b> section.</li>
                        <li>Click on the Seller's name to view their <b>address and contact information</b>.</li>
                        <li>Visit the location within the specified pickup window.</li>
                        <li>Show your <b>Order ID</b> to the vendor to confirm and receive your box.</li>
                        <li>Once collected, go back to your Order History and click <b>"Collected"</b> to finalize the
                            transaction.</li>
                        <li>Enjoy your delicious food and help reduce food waste!</li>
                    </ol>
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="headingFour">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                    What about food safety and hygiene?
                </button>
            </h2>
            <div id="collapseFour" class="accordion-collapse collapse" aria-labelledby="headingFour"
                data-bs-parent="#faqAccordion">
                <div class="accordion-body">
                    All our vendors are established food service professionals (licensed HoReCa) and must adhere to
                    strict local hygiene regulations. Surplus food is packed safely and stored appropriately before
                    pickup. We require all food to be safe for consumption at the time of pickup.
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="headingFive">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
                    When can I leave a review?
                </button>
            </h2>
            <div id="collapseFive" class="accordion-collapse collapse" aria-labelledby="headingFive"
                data-bs-parent="#faqAccordion">
                <div class="accordion-body">
                    To maintain authenticity, only verified purchasers can leave reviews. Once you successfully
                    <b>collected</b> your box, the <b>"Review"</b> button will appear in your <b>Order</b> page for the
                    items you purchased. You may review the same product every time you purchase it (due to potential
                    content variation).
                </div>
            </div>
        </div>

    </div>
</div>

<?php include('../includes/footer.php'); ?>
<?php include('../includes/end.php'); ?>